{\rtf1\ansi\ansicpg1252\cocoartf1347\cocoasubrtf570
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red26\green26\blue26;\red33\green152\blue210;\red151\green0\blue126;
}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl426

\f0\fs28 \cf2 \expnd0\expndtw0\kerning0
language: objective-c\
script: xcodebuild -workspace 3DRotationDemo\cf3 \expnd0\expndtw0\kerning0
.xcworkspace\cf2 \expnd0\expndtw0\kerning0
 -scheme 3DRotationDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=\cf4 \expnd0\expndtw0\kerning0
NO}